# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cbe3480c084bbd767157d369ef37bb6420e203d224e030c94c049ef21ed2b8cc9ad37f96620ad359a0f06faa6f9ee4dcdd0eb2fe2cabed3d35a10ce4596a4ac

test:
  secret_key_base: 05e1cf94fd6ebe7d006241ff6c65e077062005d0d7ad414fbfa28f6597054a51add880c975790876f2964995eebe64ce2bfbda8b7e65c91428a4dbafe6a42c87

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
